###consul服务端口号
server:
  port: 8081

spring:
  application:
    name: consul-consumer-Order
  ####consul注册中心地址
  cloud:
    consul:
      host: 192.168.190.130
      port: 8500
      discovery:
        #hostname: 127.0.0.1
        service-name: ${spring.application.name}
        heartbeat:
          enabled: true


